
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.VBox vbox3;

	private global::Gtk.MenuBar menubar4;

	private global::Gtk.HBox hbox5;

	private global::Gtk.VBox vbox5;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button ScanButton;

	private global::Gtk.Entry ItemBarcodeField;

	private global::Gtk.VBox vbox6;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView ScannedItemTable;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button CompleteSaleBtn;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name='menubar4'/></ui>");
		this.menubar4 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar4")));
		this.menubar4.Name = "menubar4";
		this.vbox3.Add(this.menubar4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.menubar4]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.ScanButton = new global::Gtk.Button();
		this.ScanButton.CanFocus = true;
		this.ScanButton.Name = "ScanButton";
		this.ScanButton.UseUnderline = true;
		this.ScanButton.Label = global::Mono.Unix.Catalog.GetString("Add Item");
		this.hbox7.Add(this.ScanButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.ScanButton]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.ItemBarcodeField = new global::Gtk.Entry();
		this.ItemBarcodeField.CanFocus = true;
		this.ItemBarcodeField.Name = "ItemBarcodeField";
		this.ItemBarcodeField.IsEditable = true;
		this.ItemBarcodeField.InvisibleChar = '•';
		this.hbox7.Add(this.ItemBarcodeField);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.ItemBarcodeField]));
		w4.Position = 1;
		this.vbox5.Add(this.hbox7);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		this.hbox5.Add(this.vbox5);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox5]));
		w6.Position = 0;
		this.vbox3.Add(this.hbox5);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.ScannedItemTable = new global::Gtk.TreeView();
		this.ScannedItemTable.CanFocus = true;
		this.ScannedItemTable.Name = "ScannedItemTable";
		this.ScannedItemTable.SearchColumn = 1;
		this.GtkScrolledWindow.Add(this.ScannedItemTable);
		this.vbox6.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.GtkScrolledWindow]));
		w9.Position = 0;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.CompleteSaleBtn = new global::Gtk.Button();
		this.CompleteSaleBtn.CanFocus = true;
		this.CompleteSaleBtn.Name = "CompleteSaleBtn";
		this.CompleteSaleBtn.UseUnderline = true;
		this.CompleteSaleBtn.Label = global::Mono.Unix.Catalog.GetString("Complete Sale");
		this.hbox6.Add(this.CompleteSaleBtn);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.CompleteSaleBtn]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox6.Add(this.hbox6);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox6]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox3.Add(this.vbox6);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox6]));
		w12.Position = 2;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 487;
		this.DefaultHeight = 299;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.ScanButton.Clicked += new global::System.EventHandler(this.OnScanButtonClick);
		this.CompleteSaleBtn.Clicked += new global::System.EventHandler(this.OnCompleteSaleClick);
	}
}
